config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses, only: [:index, :new, :create]
  end
  resources :doses, only: [:show, :edit, :update]

  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

# params.require(:cocktail).permit(:name) als er meerdere resultaten zijn

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<h1>Edit cocktail</h1>

<%= simple_form_for [@cocktail] do |f| %>

  <% if @cocktail.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @cocktail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1><%= f.input :name %></h1>

  <h2>Recipe</h2>
    <% @cocktail.doses.each do |dose| %>
      <tr>
        <td><%= dose.description %> <%= dose.ingredient.name %></td>
      </tr>
    <%end%>

  <div class="form-actions">
    <%= f.submit "Submit cocktail", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>

<%= link_to "New cocktail", new_cocktail_path, class: "btn btn-primary" %>
<br>
<ul list-style-type: none;>
<% @cocktails.each do |cocktail| %>
  <li><%=cocktail.name %></li>
  <li><%= link_to 'Show', cocktail %>
  <%= link_to 'Edit', edit_cocktail_path(cocktail) %>
  <%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
      <br>
<% end %>
</ul>
<!--

app/views/cocktails/new.html.erb
<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path, class: "btn btn-primary" %>

app/views/cocktails/show.html.erb
<p>
  <strong>Cocktail Name:</strong>
</p>

  <div>
    <%= @cocktail.name %>
  </div>

  <% @cocktail.doses.each do |dose| %>
    <tr>
      <td><%= dose.ingredient.name %></td>
      <td><%= dose.description %></td>
    </tr>
  <% end %>
<div>
  <%= link_to 'Edit', edit_cocktail_path(@cocktail), class: "btn btn-primary" %>
</div>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <div class="form-inputs">
    <%= f.association :ingredient %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.submit "Add dosage", class: "btn btn-primary" %>
  </div>
<% end %>

<div>
  <!-- <%= button_to 'Back', cocktails_path %> -->
  <%= link_to 'Back', cocktails_path %>
</div>

app/views/doses/new.html.erb
<h4>Add dosage</h4>

<%= simple_form_for [cocktail, dose] do |f| %>
  <div class="form-inputs">
    <%= f.association :ingredient %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.submit "Add dosage", class: "btn btn-primary" %>
  </div>
<% end %>

<!--  -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>
  </body>
</html>